name: Debug callee

on:
  workflow_call:
    secrets:
      CSC_LINK:
        required: false
      CSC_KEY_PASSWORD:
        required: false
      APPLE_API_KEY:
        required: false
      APPLE_API_KEY_ID:
        required: false
      APPLE_API_ISSUER:
        required: false
      MACOS_PROVISIONING_PROFILE:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_CLIENT_SECRET:
        required: false
      AZURE_TRUSTED_SIGNING_ENDPOINT:
        required: false
      AZURE_TRUSTED_SIGNING_ACCOUNT_NAME:
        required: false
      AZURE_TRUSTED_SIGNING_CERTIFICATE_PROFILE_NAME:
        required: false
      AZURE_TRUSTED_SIGNING_PUBLISHER_NAME:
        required: false
    inputs:
      label:
        required: true
        type: string
      runner:
        required: true
        type: string
      platform:
        required: true
        type: string
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      rust_target:
        required: true
        type: string
      resource_key:
        required: true
        type: string
      cli_archive:
        required: false
        default: false
        type: boolean
      version:
        required: true
        type: string
      ref:
        required: true
        type: string
      release_channel:
        required: true
        type: string
      relay_client_tracing:
        required: false
        default: true
        type: boolean
      clerk_publishable_key:
        required: true
        type: string
      clerk_jwt_template:
        required: true
        type: string
      clerk_cli_oauth_client_id:
        required: true
        type: string
      relay_url:
        required: true
        type: string

permissions:
  actions: read
  contents: read

jobs:
  hello:
    name: Hello ${{ inputs.label }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "hello ${{ inputs.label }}"
