name: Fork release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  desktop_linux_x64:
    name: Desktop Linux x64
    uses: ./.github/workflows/debug-callee.yml
    with:
      label: Linux x64
